apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:                  # critérios para escalar
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 2 # se a média de uso de CPU passar de 50%, escala para mais pods. Se ficar abaixo, escala para menos pods