apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2            # quantos Pods iguais criar
  selector:              # jeito de reconhecer esse Pod
    matchLabels:
      app: frontend
  template:              # receita do Pod
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jacquetech/unipdi-frontend
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend:8080" # vem do metadata.name do backend-deployment.yaml
          livenessProbe: # verifica se o Pod está vivo. Se falhar, reinicia o Pod
            httpGet:
              path: /       # get para a página principal
              port: 80
            periodSeconds: 10 # verifica a cada 10 segundos
            failureThreshold: 3 # quantos erros até considerar que o pod falhou
            initialDelaySeconds: 20 # quantos segundos espera até começar a testar o pod
          readinessProbe: # verifica se está pronto para receber tráfego. Se falhar, para de receber
            httpGet:
              path: /  # get para a página principal. Ideal ter endpoint específico para checar
              port: 80
            periodSeconds: 10 # a cada 10 segundos, verifica se o pod pode receber requisições
            failureThreshold: 3 #  quantos erros até considerar que o pod is not ready
            initialDelaySeconds: 20 # quantos segundos espera até começar a testar o pod
          
---
apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000     # range de 30000–32767
  type: NodePort

# para acessar no navegador, precisa mapear a porta 5173 (porta liberada no backend para o CORS)
# kubectl port-forward service/svc-frontend 5173:80